M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date So 02 Okt 2022 19:47:39 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-02T19:47:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.7545Y-4.7256
X5.9455Y-4.7256
T2
X5.7427Y-4.8449
X5.9573Y-4.8449
T0
M30
